---
name: GitHub-Pages

permissions:
    contents: write

on:
    push:
        branches:
            - master
            - "2.2"
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        uses: llaville/.github/.github/workflows/gh-pages.yml@master
        with:
            destination-dir: "2.2"
            force-orphan: false
            hook-script: "resources/gh-pages-hook.sh"
