---
name: GitHub-Pages

on:
    push:
        branches:
            - master
            - "1.0"
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        uses: llaville/.github/.github/workflows/gh-pages.yml@uml
        with:
            destination-dir: "1.0"
            force-orphan: true
            php-version: "8.1"
