---
name: GitHub-Pages

on:
    push:
        branches:
            - master
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        uses: llaville/.github/.github/workflows/gh-pages.yml@master
        with:
            destination-dir: ''
            php-version: "8.1"
