---
name: Unit Tests

on:
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'docs/**'
    workflow_call:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
    workflow_dispatch:
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

permissions:
    contents: read

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}
            php-version: "8.2"
            composer-options: "--prefer-dist --no-scripts"

    unit_tests:
        needs: lint_files

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    -   os: ubuntu-22.04
                        php: 8.2
                        continue-on-error: false
                    -   os: ubuntu-22.04
                        php: 8.3
                        continue-on-error: false
                    -   os: ubuntu-22.04
                        php: 8.4
                        continue-on-error: false

        name: Unit Tests

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout
                uses: actions/checkout@v4

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: phpunit:11.5

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: "highest"
                    composer-options: "--prefer-dist --no-scripts"

            -   # https://github.com/sebastianbergmann/phpunit/tree/11.5
                name: Unit tests with PHPUnit 11
                run: phpunit --do-not-cache-result --no-progress
                continue-on-error: ${{ matrix.continue-on-error }}
